CREATE DATABASE refill_studios;
USE refill_studios;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    profilePicture VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE staff (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staffRole VARCHAR(30) UNIQUE NOT NULL,
    FOREIGN KEY (userID) REFERENCES user(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (userID) REFERENCES user(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (uploaderID) REFERENCES staff(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    header VARCHAR(100) UNIQUE NOT NULL,
    postDescription VARCHAR(255) UNIQUE NOT NULL,
    attachedImage VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (uploaderID) REFERENCES user(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    commentDescription VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);